# Generated by Django 4.2.1 on 2023-07-22 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialbook', '0009_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 2, 10, 45, 977912)),
        ),
    ]
